FROM ubuntu:12.04

# Install dependencies
RUN apt-get update -y

# Install AMP for our application to load into

RUN apt-get install -y apache2
RUN apt-get install -y mysql-server
RUN apt-get install -y php 
RUN apt-get install -y libapache2-mod-php 
RUN apt-get install -y php-mcrypt 
RUN apt-get install -y php-mysql

# Install system tools/libraries

RUN apt-get install -y ssh 
RUN apt-get install -y curl
RUN apt-get install -y wget
RUN apt-get install -y nano


# Install apache and write hello world message

RUN echo “CPT-Networking to World: Hello are you there!” > /var/www/index.html

# Configure apache

RUN a2enmod rewrite
RUN chown -R www-data:www-data /var/www
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

EXPOSE 80

CMD ["/usr/sbin/apache2", "-D",  "FOREGROUND"]

